version: '3.3'

networks:
    ws_test:

services:
    php-fpm:
        build:
            context: ./php
        volumes:
            - ./src:/var/www/html
        depends_on:
            - db
        networks:
            - ws_test

    web:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
        ports:
            - 8080:80
        links:
            - php-fpm
        networks:
            - ws_test

    db:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: sw_test
            MYSQL_USER: dev
            MYSQL_PASSWORD: secret
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        ports:
            - 6033:3306
        networks:
            - ws_test

    adminer:
        image: adminer
        restart: always
        ports:
            - 8765:8080
        networks:
            - ws_test

    redis:
        image: redis:alpine
        networks:
            - ws_test
